name: Publish Package on Tag

on:
  push:
    tags:
      - 'v*'  # This triggers the workflow on tags starting with 'v'

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Run NPM CI
      run: npm ci

    - name: Build the package
      run: npm run build
      
    - name: Publish To NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}